# Generated by Django 3.2.9 on 2024-02-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('marca_tractor', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_placas_tractor', models.CharField(blank=True, max_length=50, null=True)),
                ('no_economico', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_caja', models.CharField(blank=True, max_length=40, null=True)),
                ('numero_placas_caja', models.CharField(blank=True, max_length=30, null=True)),
                ('es_exportacion', models.BooleanField(blank=True, null=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='forms.contactoclave')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='forms.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DS_doc_embarque', models.BooleanField(blank=True, null=True)),
                ('DS_aut_embarque', models.BooleanField(blank=True, null=True)),
                ('DS_has_sello', models.BooleanField(blank=True, null=True)),
                ('DS_sello', models.CharField(blank=True, max_length=40, null=True)),
                ('factura', models.CharField(blank=True, max_length=80, null=True)),
                ('numero_pallets', models.CharField(blank=True, max_length=30, null=True)),
                ('CGTS_luces_frente', models.BooleanField(blank=True, null=True)),
                ('CGTS_luces_traseras', models.BooleanField(blank=True, null=True)),
                ('CGTS_motor', models.BooleanField(blank=True, null=True)),
                ('CGTS_tubo_escape', models.BooleanField(blank=True, null=True)),
                ('CGTS_exterior_chasis', models.BooleanField(blank=True, null=True)),
                ('CGTS_fugas_aceite', models.BooleanField(blank=True, null=True)),
                ('CGTS_techo_int_ext', models.BooleanField(blank=True, null=True)),
                ('CGTS_puertas_int_ext', models.BooleanField(blank=True, null=True)),
                ('CGTS_paredes_laterales', models.BooleanField(blank=True, null=True)),
                ('CGTS_parachoques', models.BooleanField(blank=True, null=True)),
                ('CGTS_piso', models.BooleanField(blank=True, null=True)),
                ('CGTS_patines', models.BooleanField(blank=True, null=True)),
                ('CGTS_quinta_rueda', models.BooleanField(blank=True, null=True)),
                ('CGTS_tanque_combustible', models.BooleanField(blank=True, null=True)),
                ('CGTS_tanques_aire', models.BooleanField(blank=True, null=True)),
                ('CGTS_llantas_rines', models.BooleanField(blank=True, null=True)),
                ('CGTS_ejes', models.BooleanField(blank=True, null=True)),
                ('CGTS_cabina', models.BooleanField(blank=True, null=True)),
                ('CGTS_comopartimientos_herramientas', models.BooleanField(blank=True, null=True)),
                ('CGTS_agricolas', models.BooleanField(blank=True, null=True)),
                ('CGTS_olores_ext', models.BooleanField(blank=True, null=True)),
                ('CGTS_humedad', models.BooleanField(blank=True, null=True)),
                ('CGTS_obj_sust_ext', models.BooleanField(blank=True, null=True)),
                ('comentarios_salida', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_salida', models.DateTimeField(auto_now_add=True, null=True)),
                ('embarque_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.embarque')),
                ('guardia_salida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.guardia')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionCanina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patio', models.CharField(blank=True, max_length=40, null=True)),
                ('cliente', models.CharField(blank=True, max_length=40, null=True)),
                ('nombre_k9', models.CharField(blank=True, max_length=50, null=True)),
                ('PR_defensa', models.BooleanField(blank=True, null=True)),
                ('PR_motor', models.BooleanField(blank=True, null=True)),
                ('PR_piso_cabina', models.BooleanField(blank=True, null=True)),
                ('PR_tanque_combustible', models.BooleanField(blank=True, null=True)),
                ('PR_llantas_rines', models.BooleanField(blank=True, null=True)),
                ('PR_flecha', models.BooleanField(blank=True, null=True)),
                ('PR_cabina', models.BooleanField(blank=True, null=True)),
                ('PR_tanque_aire', models.BooleanField(blank=True, null=True)),
                ('PR_mofles', models.BooleanField(blank=True, null=True)),
                ('PR_equipo_refrigeracion', models.CharField(blank=True, max_length=10, null=True)),
                ('PR_quinta_rueda', models.BooleanField(blank=True, null=True)),
                ('PR_chasis', models.BooleanField(blank=True, null=True)),
                ('PR_puertas_traseras', models.BooleanField(blank=True, null=True)),
                ('PR_paredes_techo', models.BooleanField(blank=True, null=True)),
                ('PR_piso_caja', models.BooleanField(blank=True, null=True)),
                ('descripcion_hallazgo', models.CharField(blank=True, max_length=1000, null=True)),
                ('embarque_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.embarque')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DE_tarjeta_circulacion', models.BooleanField(blank=True, null=True)),
                ('DE_seguro_obligatorio', models.BooleanField(blank=True, null=True)),
                ('DE_placas_fisicas', models.BooleanField(blank=True, null=True)),
                ('DE_licencia_federal', models.BooleanField(blank=True, null=True)),
                ('CGTE_luces_frente', models.BooleanField(blank=True, null=True)),
                ('CGTE_luces_traseras', models.BooleanField(blank=True, null=True)),
                ('CGTE_motor', models.BooleanField(blank=True, null=True)),
                ('CGTE_tubo_escape', models.BooleanField(blank=True, null=True)),
                ('CGTE_exterior_chasis', models.BooleanField(blank=True, null=True)),
                ('CGTE_fugas_aceite', models.BooleanField(blank=True, null=True)),
                ('CGTE_techo_int_ext', models.BooleanField(blank=True, null=True)),
                ('CGTE_puertas_int_ext', models.BooleanField(blank=True, null=True)),
                ('CGTE_paredes_laterales', models.BooleanField(blank=True, null=True)),
                ('CGTE_parachoques', models.BooleanField(blank=True, null=True)),
                ('CGTE_piso', models.BooleanField(blank=True, null=True)),
                ('CGTE_patines', models.BooleanField(blank=True, null=True)),
                ('CGTE_quinta_rueda', models.BooleanField(blank=True, null=True)),
                ('CGTE_tanque_combustible', models.BooleanField(blank=True, null=True)),
                ('CGTE_tanques_aire', models.BooleanField(blank=True, null=True)),
                ('CGTE_llantas_rines', models.BooleanField(blank=True, null=True)),
                ('CGTE_ejes', models.BooleanField(blank=True, null=True)),
                ('CGTE_cabina', models.BooleanField(blank=True, null=True)),
                ('CGTE_comopartimientos_herramientas', models.BooleanField(blank=True, null=True)),
                ('CGTE_agricolas', models.BooleanField(blank=True, null=True)),
                ('CGTE_olores_ext', models.BooleanField(blank=True, null=True)),
                ('CGTE_humedad', models.BooleanField(blank=True, null=True)),
                ('CGTE_obj_sust_ext', models.BooleanField(blank=True, null=True)),
                ('comentarios_entrada', models.CharField(blank=True, max_length=50, null=True)),
                ('embarque_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.embarque')),
                ('guardia_entrada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.guardia')),
            ],
        ),
        migrations.AddField(
            model_name='embarque',
            name='guardia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.guardia'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='linea_de_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linea_de_caja', to='forms.linea'),
        ),
        migrations.AddField(
            model_name='embarque',
            name='linea_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linea_transporte', to='forms.linea'),
        ),
    ]
