# Generated by Django 3.2.9 on 2021-11-19 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardia', models.CharField(blank=True, max_length=50, null=True)),
                ('operador', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_transporte', models.CharField(blank=True, max_length=50, null=True)),
                ('marca_tractor', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_placas', models.CharField(blank=True, max_length=50, null=True)),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.formulario')),
            ],
        ),
    ]
