# Generated by Django 3.2.9 on 2022-10-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='DS_has_sello',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
