# Generated by Django 3.2.9 on 2023-03-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20221107_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='numero_pallets',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='numero_sello',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='sello_entregado_a',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='numero_cajas_embarque',
        ),
        migrations.AddField(
            model_name='salida',
            name='factura',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='numero_pallets',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
