# Generated by Django 3.2.9 on 2022-11-30 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20221107_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarque',
            name='numero_sello',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='sello_entregado_a',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='numero_cajas_embarque',
        ),
    ]
