# Generated by Django 3.2.9 on 2023-04-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20221130_0220'),
        ('forms', '0006_auto_20230314_1627'),
    ]

    operations = [
    ]
