# Generated by Django 3.2.9 on 2022-09-12 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0002_auto_20211122_1649'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('hour', models.TimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='incidence')),
                ('incidencias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.checklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
