# Generated by Django 3.2.9 on 2024-02-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(default='', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('hour', models.TimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='incidence')),
                ('embarque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='forms.embarque')),
                ('incidence_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidence.incidencetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
