# Generated by Django 3.2.9 on 2022-10-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='incidencias',
        ),
    ]
