# Generated by Django 3.2.9 on 2022-10-25 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('in_out', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerinout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='registerinout',
            name='option',
        ),
        migrations.RemoveField(
            model_name='registerinout',
            name='time',
        ),
        migrations.AddField(
            model_name='registerinout',
            name='dt_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registerinout',
            name='dt_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='InOut',
        ),
    ]
