# Generated by Django 3.2.9 on 2022-10-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_out', '0002_auto_20221025_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerinout',
            name='dt_out',
            field=models.DateTimeField(null=True),
        ),
    ]
