# Generated by Django 3.2.9 on 2022-10-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_worker_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workertype',
            old_name='type',
            new_name='worker_type',
        ),
    ]
