# Generated by Django 3.2.9 on 2022-10-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_workertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online_in_app',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
